### ISSUE TITLE
Add Continuous Integration on Windows

### ISSUE THREAD

**Issue by NicolasRitouet** [deployd/deployd-cli#17]
It would be great to test `deployd-cli` on windows automatically. That would allow us to make sure that new features are still working on a windows environment.
We are using travisCi at the moment to run our suite of test, but they can't run these on Windows.
We should use another service like `appveyor` to run our tests on a Windows environment.

# Todo

- [ ] Create [an `appveyor.yml` file](https://www.appveyor.com/docs/lang/nodejs-iojs/)
- [ ] hope that the build pass without doing any change
- [ ] If not, do the necessary changes to make the build pass
- [ ] Once it works, add a nice appveyor badge in the readme

**Comment by poldiwa** [comment]
Hello @NicolasRitouet , it's gonna be my first attempt to contribute on open source, I would like to ask if the badge is gonna be the badge for my own fork or for this repo.

**Comment by NicolasRitouet** [comment]
@poldiwa great 👍 
Sure, take this one and feel free to come on the chat (https://gitter.im/deployd/deployd) if you need help.

**Comment by poldiwa** [comment]
@NicolasRitouet I already did it, should I post a PR? Maybe you can check it.

**Comment by NicolasRitouet** [comment]
@poldiwa yes, please, send us a PR (use this course to know how to do it: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)
I just added appveyor to the project, just update the badge to deployd/deployd-cli and that should be good 👍
